Link Shortener/links/urls.py
from django.urls import path
from . import views

app_name = 'links'

urlpatterns = [
    path('',views.CreateLink.as_view(), name = 'create-link'),
    path('shortener/<str:tag>/',views.RedirectLink.as_view(), name='redirect'),
    path('not-found/',views.NotFound, name='not-found'),
    path('my-links/',views.ListLink.as_view(),name='my-links')
]

Link Shortener/shortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('links.urls')),
    path('',include('user.urls')),
]

Link Shortener/user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'user'

urlpatterns = [
    path('login/',views.LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page = 'links:create-link'),name='logout'),
    path('register/',views.RegisterView.as_view(),name='register'),
]

Link Shortener/links/models.py
from django.db import models
from django.conf import settings


class Link(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,null=True,blank=True)
    original_link = models.URLField()
    tag = models.CharField(max_length=255,unique=True)
    visits = models.PositiveIntegerField(default=0)

Link Shortener/user/models.py
from django.db import models

Link Shortener/links/forms.py
from django import forms
from django.core.validators import MinLengthValidator
from .models import Link

def tag_validator(value):
    if Link.objects.filter(tag = value).exists():
        return forms.ValidationError('Link with this tag already exists')


class CreateLinkform(forms.ModelForm):
    original_link= forms.URLField(widget= forms.URLInput(attrs ={'class':'form-control'}))
    tag = forms.CharField(validators=[tag_validator,MinLengthValidator(2,'Tag should have min length 2')], widget=forms.TextInput(attrs ={'class':'form-control'}))

    class Meta:
        model = Link
        fields = ('original_link','tag')


    

Link Shortener/user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth import password_validation

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': ''}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': '',
        }
    ))

    error_messages = {
        "invalid_login": (
            "Please enter a correct %(username)s and password."
        ),
        "inactive": ("This account is inactive."),
    }


class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': ''}))
    password1 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={
            'class': 'form-control',
            'placeholder': '',
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
            'class': 'form-control',
            'placeholder': '',
        }),
        strip=False,
        help_text=("Enter the same password as before, for verification."),
    )


    class Meta(UserCreationForm.Meta):
        fields = ("username",)
        field_classes = {}

Link Shortener/links/views.py
from django.shortcuts import render,redirect
from django.views.generic import RedirectView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Link
from .forms import CreateLinkform

class RedirectLink(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        if Link.objects.filter(tag = kwargs.get('tag')).exists():
            link = Link.objects.get(tag = kwargs['tag'])
            link.visits += 1
            link.save()
            return link.original_link
        return redirect(to='links:not-found').url


def NotFound(request):
    return render(request,'links/not_found.html',{})


class CreateLink(CreateView):
    template_name = 'links/create_link.html'
    context_object_name = 'links'
    form_class = CreateLinkform
    
    def form_valid(self, form):
        self.object = form.save()
        if self.request.user.is_authenticated:
            link = Link.objects.get(tag = form.instance.tag)
            link.user = self.request.user
            link.save()
        # Does not redirect if valid
        #return HttpResponseRedirect(self.get_success_url())

        # Render the template
        # get_context_data populates object in the context 
        # or you also get it with the name you want if you define context_object_name in the class
        return self.render_to_response(self.get_context_data(form=form,shortened_url=str(self.request.build_absolute_uri('/shortener/' + form.instance.tag + '/'))))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shortened_url'] = kwargs.get('shortened_url')
        return context


class ListLink(LoginRequiredMixin,ListView):
    context_object_name = 'links'
    template_name = 'links/my_links.html'
    paginate_by = 5

    def get_queryset(self):
        return Link.objects.filter(user = self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['prefix'] = self.request.build_absolute_uri('/shortener/')
        return context

Link Shortener/user/views.py
from django.contrib.auth import login
from django.contrib.auth.views import LoginView as BaseLoginView
from django.views.generic import FormView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from .forms import UserLoginForm, CreateUserForm


class LoginView(BaseLoginView):
    fields = '__all__'
    redirect_authenticated_user = True
    template_name = 'user/login.html'
    form_class = UserLoginForm
    
    def get_success_url(self) -> str:
        return reverse_lazy('links:create-link')


class RegisterView(FormView):
    form_class = CreateUserForm
    redirect_authenticated_user = True
    template_name = 'user/register.html'

    def get_success_url(self) -> str:
        return reverse_lazy('links:create-link')
    
    def form_valid(self, form):
        user  = form.save()
        if user is not None:
            login(self.request,user)
        return super().form_valid(form)
    
    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('links:create-link')
        return super().get(request, *args, **kwargs)

Link Shortener/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shortener</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" 
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <style>
        body {
            background: url("{% static 'images/david-becker-crs2vlkSe98-unsplash.jpg' %}") no-repeat center center/ cover;
        }
    </style>
</head>
<body class="vh-100 text-light px-2">
    <nav class="container navbar navbar-dark bg-dark mb-5">
        <div class="container">
            <a class="navbar-brand" href="{% url 'links:create-link' %}">Small URL</a>
                <span class="navbar-nav flex-row">
                    {% if request.user.is_authenticated %}
                    <span class="nav-item mx-2">
                        <a class="nav-link" aria-current="page" href="#">{{request.user}}</a>
                    </span>
                    <span class="nav-item mx-2">
                        <a class="nav-link active" aria-current="page" href="{% url 'links:my-links' %}">My Links</a>
                    </span>
                    <span class="nav-item mx-2">
                        <a class="nav-link active" href="{% url 'user:logout' %}">Logout</a>
                    </span>
                    {% else %}
                    <span class="nav-item mx-2">
                        <a class="nav-link active" href="{% url 'user:login' %}">Login</a>
                    </span>
                    <span class="nav-item mx-2">
                        <a class="nav-link active" href="{% url 'user:register' %}">Register</a>
                    </span>
                    {% endif %}
                </ul>
        </div>
    </nav>
    <div class="container bg-dark bg-opacity-50 py-2 border border-dark rounded">
        {% block content %}

        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</body>
</html>

Link Shortener/templates/links/create_link.html
{% extends 'base.html' %}

{% block content %}
<p class="fs-4 mb-2">Shorten your links here</p> <br>
<form action = "" method = "post">
    {% csrf_token %}
        <div class = "mb-2">
            <label for='original-link'>Enter Url to Shorten</label>
            {{form.original_link}}
            {% if form.original_link.errors %}
                {% for error in form.original_link.errors %}
                    <span class="row mx-2 fw-semibold">{{error}}</span>
                {% endfor %}
            {% endif %}
        </div>
        <div class = "mb-3">
            <label for="tag">Enter Tag</label>
            {{form.tag}}
            {% if form.tag.errors %}
                {% for error in form.tag.errors %}
                    <span class="row mx-2 fw-semibold">{{error}}</span>
                {% endfor %}
            {% endif %}
        </div>
    <input type="submit" value=Submit class="btn btn-primary">
</form>
{% if shortened_url %}
    <div class="row text-center">
        <span class="fs-6">
            Shortened url: 
            <a href="{{shortened_url}}" class="shortened-link bg-dark bg-opacity-75">{{shortened_url}}</a>
            <button class="copy btn bg-transparent" onclick="copyToClipboard('.shortened-link')"><i class="fa fa-regular fa-copy text-white"></i></button>
        </span>
    </div>
    <script>
        function copyToClipboard(element) {
            var $temp = $("<input>");
            $("body").append($temp);
            $temp.val($(element).text()).select();
            document.execCommand("copy");
            $temp.remove();
        }
    </script>
{% endif %}
{% endblock content %}

Link Shortener/templates/links/my_links.html
{% extends 'base.html' %}

{% block content %}
    {% if links %}
    <div class="table-responsive">
        <table class="table text-light">
            <thead>
                <tr>
                    <td scope="col">Original URL</td>
                    <td scope="col">Small URL</td>
                    <td scope="col">Visits</td>
                </tr>
            </thead>
            <tbody>
            {% for link in links %}
                <tr>
                    <th scope="row">{{link.original_link}}</th>
                    <td>{{prefix}}{{link.tag}}/</td>
                    <td>{{link.visits}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <div class="row text-center">
        <p class="fs-4 mb-3">Looks like you don't have any URL yet</p> <br>
        <p class="fs-6">Shorten your urls  <a href="{% url 'links:create-link' %}">here</a></p>
    </div>
    {% endif %}
    {% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="{% url 'links:my-links' %}?page={{ page_obj.previous_page_number }}" class="text-decoration-none text-light">    
                    <button class="btn btn-primary">Previous</button>
                </a>
            {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
            {% if page_obj.has_next %}
                <a href="{% url 'links:my-links' %}?page={{ page_obj.next_page_number }}" class="text-decoration-none text-light">
                    <button class="btn btn-primary">Next</button>
                </a>
            {% endif %}
        </span>
    </div>
    {% endif %}
{% endblock content %}

Link Shortener/templates/links/not_found.html
{% extends 'base.html' %}

{% block content %}
<div class="row text-center">
    <p class="fs-4 mb-3">Oops! Looks like no such Url exists</p> <br>
    <p class="fs-6">Shorten your urls  <a href="{% url 'links:create-link' %}">here</a></p>
</div>
{% endblock content %}

Link Shortener/templates/user/login.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <span class="row mx-2 fw-semibold">{{error}}</span>
    {% endfor %}
    <div class="form-group">
        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}
        {% for error in form.username.errors %}
            <span class="row mx-2 fw-semibold">{{error}}</span>
        {% endfor %}
    </div>
    <div class="form-group mb-2">
        <label for="{{ form.password.id_for_label }}">Password:</label>
        {{ form.password }}
        {% for error in form.password.errors %}
            <span class="row mx-2 fw-semibold">{{error}}</span>
        {% endfor %}
    </div>
    <button class="btn btn-primary" type="submit">Login</button>
</form>
<p>Don't have an account? <a href="{% url 'user:register' %}">Register</a></p>

{% endblock content %}

Link Shortener/templates/user/register.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <span class="row mx-2 fw-semibold">{{error}}</span>
    {% endfor %}
    <div class="form-group">
        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}
        {% for error in form.username.errors %}
            <span class="row mx-2 fw-semibold">{{error}}</span>
        {% endfor %}
    </div>
    <div class="form-group">
        <label for="{{ form.password1.id_for_label }}">Password:</label>
        {{ form.password1 }}
        {% for error in form.password1.errors %}
            <span class="row mx-2 fw-semibold">{{error}}</span>
        {% endfor %}
    </div>
    <div class="form-group mb-2">
        <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
        {{ form.password2 }}
        {% for error in form.password2.errors %}
            <span class="row mx-2 fw-semibold">{{error}}</span>
        {% endfor %}
    </div>
    <button class="btn btn-primary" type="submit">Login</button>
</form>
<p>Already have an account? <a href="{% url 'user:login' %}">Login</a></p>

{% endblock content %}